<?php
require_once("../etc/conf.php");
if (!isset($_SERVER['HTTP_REFERER']) || stripos($_SERVER['HTTP_REFERER'],$site_name) ==FALSE) 
{	$actual_link = "$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
	header("Location: ".$port_type."://".str_replace($site_name."/",$site_name."/?",$actual_link)."");
	die();
}
?>
	<div style="margin-top:50px; margin-left: 20px; margin-right: 40px;">
	<p style="font-size:18px"><b>Noteb API - General information</b></p>
	<p>Noteb gives free limited access to its laptop database to anyone willing to develop or enhanced third party applications or websites based on the information provided here.<br><br>
	<p style="font-size:18px"><b>Access</b></p>
	In order to access the Noteb API, it is necessary to have an API key. For testing purposes, in the API documentation there is a public API key with very limited usability. However, if you are serious about developing with the Noteb API, we advise to contact us at <span class='contactEmail' onclick='mail_to("office");'></span> and request an individual unique API key.
	<br><br>
	<p style="font-size:18px"><b>Usage conditions</b></p>
	 The legal conditions governing the usage of the Noteb API are the Noteb API Terms of Service Agreement. <b>By using the Noteb API, you agree to <a href="https://<?php echo $site_name;?>/?public/api_tos.php">Noteb API Terms of Service Agreement</a>.</b>
	<br><br>
	All API keys are provided free of charge and come with a limited number of <b>daily requests per key</b>. The number of available daily requests automatically resets to its maximum daily allowance once every 24 hours. The maximum value of requests should be enough for developing and light usage of the Noteb database. Increasing the maximum value of daily requests is possible, but may require a small monthly fee in order to cover our hosting costs. The fee dependents on the server load generated by requests from the API key.
	<br><br>
	If a website or application, developed using the Noteb API, becomes available to public or is used for commercial purposes, it is necessary to acknowledge Noteb as a provider of information and place a visible link to Noteb on pages that request information from Noteb API. Wherever these conditions apply, it is necessary to include one of the following elements:<br><br>
	<a href="https://noteb.com" style="font-weight: bold;color:#3f8f86;">Powered by noteb.com</a><br>Code: <pre>&lt;a href="https://noteb.com" style="font-weight: bold;color:#3f8f86;"&gt;Powered by noteb.com&lt;/a&gt;</pre>
	<br>
	or
	<br>
	<img src="res/img/logo/logo_noteb.png" width="149" height="149">
	<br>
	<p style="font-size:18px"><b>Technical aspects</b></p>
		The API of Noteb is based on POST requests to Noteb's web service, which replays with JSON structured data.<br>
		Currently the API only supports methods for the retrieval of laptop model information, including all technical details, available configurations, prices, battery life and Noteb rating. Other functionalities may be developed upon request.<br>
		For further details, please consult the API documentation. 
	 <br><br>
	 	<p style="font-size:18px"><b>Termination of service</b></p>
	Usage of Noteb database data for malicious purposes can and will lead to termination or suspension of access to Noteb web service.<br>
	Attempts to circumvent API limitations and designed functionalities can and will lead to termination or suspension of access to Noteb web service.<br>
	Any unauthorised access of web service and unauthorised API requests can and will lead to termination or suspension of access to Noteb web service. 
		<br><br>

	 <p style="font-size:18px"><b>Documentation</b></p>
	 <b><a href="https://<?php echo $site_name;?>/res/doc/noteb_API_documentation.pdf">Download Noteb API documentation here</a></b><br> <br>
	 
	
	 </div>
	 <script type="text/javascript">
	 $(document).ready(function(){
	  actbtn("USER");
	  document.title="Noteb - API";
	 });
	 </script>

<?php include_once("../etc/scripts_pages.php"); ?>